### ISSUE TITLE
MSstatsTMT does not work after dplyr update to 1.0.2.

### ISSUE THREAD

**Issue by pavel-shliaha** [Vitek-Lab/MSstatsTMT#13]
I updated dplyr to 1.0.2 and MSstatsTMT. The mistake it returns is:

** Negative log2 intensities were replaced with NA.
Summarizing for Run : all.raw ( 1  of  1 )
Error in `[.data.table`(raw, , require.col) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 'require.col' is not found. Perhaps you intended DT[, ..require.col]. This difference to data.frame is deliberate and explained in FAQ 1.1.

the same code works with dplyr 0.8.3

**Comment by huang704** [comment]
This error existed in old version of MSstatsTMT due to the update of R. It has been fixed in the latest MSstatsTMT. You can update your R version (https://cloud.r-project.org/) and re-install MSstatsTMT 1.6.3 from Bioconductor (http://bioconductor.org/packages/release/bioc/html/MSstatsTMT.html).

**Comment by pavel-shliaha** [comment]
I have reinstalled the MSstatsTMT package, but the problem still persists. Please update the dplyr package and check if it works on your computer:

[PSMTable.zip](https://github.com/Vitek-Lab/MSstatsTMT/files/5293136/PSMTable.zip)

the code:

`PSMTable <- read.csv ("PSMTable.csv")
protQuant  <- proteinSummarization(PSMTable, method="msstats")`

error: 

** Negative log2 intensities were replaced with NA.
Summarizing for Run : all.raw ( 1  of  1 )
Error in `[.data.table`(raw, , require.col) : 
  j (the 2nd argument inside [...]) is a single symbol but column name 'require.col' is not found. Perhaps you intended DT[, ..require.col]. This difference to data.frame is deliberate and explained in FAQ 1.1.

**Comment by huang704** [comment]
The version of dplyr on my computer is 1.0.2. And I run the code without any problem on my computer. Can you show the version of MSstatsTMT you are using? You can run the command **sessionInfo()** to get the package version info.

**Comment by pavel-shliaha** [comment]
I have MSstatsTMT_1.4.6.

**Comment by huang704** [comment]
It seems like you didn't install the latest version of MSstatsTMT (>= 1.6.2). You need to first update R and then MSstatsTMT. You can update your R version (https://cloud.r-project.org/) and re-install MSstatsTMT 1.6.3 from Bioconductor (http://bioconductor.org/packages/release/bioc/html/MSstatsTMT.html).
