### ISSUE TITLE
annotation.pd file not accepted

### ISSUE THREAD

**Issue by gigi-mt** [Vitek-Lab/MSstatsTMT#75]
Hi everyone. 
I am trying to run MSstats TMT for a large-scale proteomics study but am running into below error within R 4.3.1 and the newest version of R studio.

Error in .mergeAnnotation(input, annotation) : 
  ** Please check the annotation file. The channel name must be matched with that in input data.

I checked the annotation file and am using the same format as in the example file. I tried multiple ways of annotating the channels, but receive the same error. 

The file size is too big to upload as attachment. Is there another way I can share with you?

I was using a previous MSstatsTMT version, but decided to upgrade. It is likely an easy fix, but I cannot seem to find the problem. 

Thanks for your help.

**Comment by mstaniak** [comment]
Please just send me unique(annotation$Channel) and column names of the input file, it should be enough to figure out what is going wrong. Thanks for reporting the issue.

**Comment by gigi-mt** [comment]
Hi Mateusz.

Thank you for looking into this. Attached the first lines of the input file, as well as the annotation file I wrote.


Here a screenshot of the data environment to give you an idea of the data size of this project.

 [cid:4e2ee817-16ff-45ea-b3a1-19beb69a5279]


Thanks again.

G

**Comment by mstaniak** [comment]
Hi, I see, this looks like the standard input,  what about unique values of Channel columns in the annotation file?

**Comment by gigi-mt** [comment]
Attached the annotation file.

Thanks.
G

________________________________
Von: Mateusz Staniak ***@***.***>
Gesendet: Donnerstag, 17. August 2023 09:13
An: Vitek-Lab/MSstatsTMT ***@***.***>
Cc: gigi-mt ***@***.***>; Author ***@***.***>
Betreff: Re: [Vitek-Lab/MSstatsTMT] annotation.pd file not accepted (Issue #75)


Hi, I see, this looks like the standard input, what about unique values of Channel columns in the annotation file?

**Comment by mstaniak** [comment]
Unfortunately, I can't see the attachment, I think it happened before with e-mail replies on GitHub. Could you please try sending it directly (e-mail can be seen in package documentation/Bioc page) or attaching here directly?

**Comment by gigi-mt** [comment]
sorry for this. Let's try again

[annotation.pd.csv](https://github.com/Vitek-Lab/MSstatsTMT/files/12369760/annotation.pd.csv)

**Comment by mstaniak** [comment]
Hi, now I see it, please remove the "Abundance: " (includes space) portion of Channel column. This should fix the problem. We remove that part from column names automatically.

**Comment by gigi-mt** [comment]
The wonders of R :) 
I had tried this format, as it is the one provided in the example file, but did not resolve the issue. From previous workshops I attended I remembered that the channel name needs to be exactly as in the input.pd file. I tried hundreds of combinations before I posted this...
Anyway, Mateusz thank you, it runs smoothly now! 
Thanks!!!!

**Comment by mstaniak** [comment]
Glad it worked, thanks for reaching out
